# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
target 'Swift教程' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
   pod 'SDWebImage', '~> 4.3.3'
	pod 'SnapKit', '~> 4.0.0'
   pod 'Kingfisher', '~> 4.7.0'
pod 'SwiftyJSON', '~> 4.1.0'
pod 'Alamofire', '~> 4.7.2'
  # Pods for Swift教程
  target 'Swift教程Tests' do



    inherit! :search_paths
    # Pods for testing
  end

  target 'Swift教程UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
